In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [2]:
from google.colab import files

uploaded = files.upload()

df = pd.read_excel(next(iter(uploaded)))

Saving Indian Population Dataset.xlsx to Indian Population Dataset.xlsx

In [3]:
df.head()

         State Region  Population  Area_km2  Literacy_Rate  Density
0    Karnataka  South    67562686    191791          75.86      834
1   Tamil Nadu  South    72147030    130058          24.56      349
2       Kerala  South    35699443     38863          21.66      245
3  Maharashtra   West   124904071    307713          90.97      653
4        Delhi  North    16787941      1484          78.09      765

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   State          10 non-null     object
 1   Region         10 non-null     object
 2   Population     10 non-null     int64
 3   Area_km2       10 non-null     int64
 4   Literacy_Rate  10 non-null     float64
 5   Density        10 non-null     int64
dtypes: float64(1), int64(3), object(2)
memory usage: 612.0+ bytes

In [5]:
df.fillna(df.mean(numeric_only=True), inplace=True)

In [6]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

for col in df.select_dtypes(include='object').columns:
    df[col] = encoder.fit_transform(df[col])

In [7]:
df['Target'] = (df['Population'] > df['Population'].median()).astype(int)

In [8]:
X = df.drop("Target", axis=1)

y = df["Target"]

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [10]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [11]:
svm = SVC(kernel='rbf', C=1)

svm.fit(X_train, y_train)

SVC(C=1)

In [12]:
svm_pred = svm.predict(X_test)

In [13]:
print("SVM Accuracy")

print(accuracy_score(y_test, svm_pred))

SVM Accuracy
0.0

In [14]:
print(confusion_matrix(y_test, svm_pred))

[[0 0]
 [2 0]]

In [15]:
print(classification_report(y_test, svm_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       0.0
           1       0.00      0.00      0.00       2.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00       2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [16]:
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)

KNeighborsClassifier()

In [17]:
knn_pred = knn.predict(X_test)

In [18]:
print("KNN Accuracy")

print(accuracy_score(y_test, knn_pred))

KNN Accuracy
0.5

In [19]:
print(confusion_matrix(y_test, knn_pred))

[[0 0]
 [1 1]]

In [20]:
print(classification_report(y_test, knn_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.50      0.67         2

    accuracy                           0.50         2
   macro avg       0.50      0.25      0.33         2
weighted avg       1.00      0.50      0.67         2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [21]:
print("SVM Accuracy :", accuracy_score(y_test, svm_pred))

print("KNN Accuracy :", accuracy_score(y_test, knn_pred))

SVM Accuracy : 0.0
KNN Accuracy : 0.5

In [23]:
max_k = min(10, len(X_train))

scores = []

for k in range(1, max_k + 1):
    model = KNeighborsClassifier(n_neighbors=k)
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    scores.append(accuracy_score(y_test, pred))

for i, score in enumerate(scores, 1):
    print(f"K = {i}, Accuracy = {score:.2f}")

K = 1, Accuracy = 0.50
K = 2, Accuracy = 0.50
K = 3, Accuracy = 0.50
K = 4, Accuracy = 0.50
K = 5, Accuracy = 0.50
K = 6, Accuracy = 0.00
K = 7, Accuracy = 0.00
K = 8, Accuracy = 0.00

In [24]:
for i,score in enumerate(scores,1):

    print("K =",i," Accuracy =",score)

K = 1  Accuracy = 0.5
K = 2  Accuracy = 0.5
K = 3  Accuracy = 0.5
K = 4  Accuracy = 0.5
K = 5  Accuracy = 0.5
K = 6  Accuracy = 0.0
K = 7  Accuracy = 0.0
K = 8  Accuracy = 0.0

In [25]:
svm2 = SVC(kernel='linear', C=0.5)

svm2.fit(X_train,y_train)

pred2 = svm2.predict(X_test)

print(accuracy_score(y_test,pred2))

1.0

In [26]:
comparison = pd.DataFrame({

    "Model":["SVM","KNN"],

    "Accuracy":[
        accuracy_score(y_test,svm_pred),
        accuracy_score(y_test,knn_pred)
    ]

})

comparison

  Model  Accuracy
0   SVM       0.0
1   KNN       0.5