In [1]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import (
    train_test_split,
    GridSearchCV,
    RandomizedSearchCV
)

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score

print("All libraries imported successfully!")

All libraries imported successfully!

In [2]:
from google.colab import files
uploaded = files.upload()

Saving Indian Population Dataset.xlsx to Indian Population Dataset.xlsx

In [3]:
import pandas as pd

df = pd.read_excel("Indian Population Dataset.xlsx")

df.head()

         State Region  Population  Area_km2  Literacy_Rate  Density
0    Karnataka  South    67562686    191791          75.86      834
1   Tamil Nadu  South    72147030    130058          24.56      349
2       Kerala  South    35699443     38863          21.66      245
3  Maharashtra   West   124904071    307713          90.97      653
4        Delhi  North    16787941      1484          78.09      765

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   State          10 non-null     object
 1   Region         10 non-null     object
 2   Population     10 non-null     int64
 3   Area_km2       10 non-null     int64
 4   Literacy_Rate  10 non-null     float64
 5   Density        10 non-null     int64
dtypes: float64(1), int64(3), object(2)
memory usage: 612.0+ bytes

In [5]:
from sklearn.preprocessing import LabelEncoder

df_encoded = df.copy()

le = LabelEncoder()

df_encoded["State"] = le.fit_transform(df_encoded["State"])
df_encoded["Region"] = le.fit_transform(df_encoded["Region"])

df_encoded.head()

   State  Region  Population  Area_km2  Literacy_Rate  Density
0      3       2    67562686    191791          75.86      834
1      7       2    72147030    130058          24.56      349
2      4       2    35699443     38863          21.66      245
3      5       3   124904071    307713          90.97      653
4      1       1    16787941      1484          78.09      765

In [6]:
X = df_encoded.drop("Region", axis=1)
y = df_encoded["Region"]

print("Features Shape:", X.shape)
print("Target Shape:", y.shape)

Features Shape: (10, 5)
Target Shape: (10,)

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (8, 5)
Testing data: (2, 5)

In [8]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

model = RandomForestClassifier(random_state=42)

param_grid = {
    "n_estimators": [50, 100],
    "max_depth": [2, 3, 5],
    "min_samples_split": [2, 4]
}

grid_search = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    cv=2,
    scoring="accuracy",
    n_jobs=-1
)

grid_search.fit(X_train, y_train)

print("Best Parameters:", grid_search.best_params_)
print("Best Score:", grid_search.best_score_)

Best Parameters: {'max_depth': 2, 'min_samples_split': 4, 'n_estimators': 50}
Best Score: 0.25

In [9]:
from sklearn.model_selection import RandomizedSearchCV

random_search = RandomizedSearchCV(
    estimator=model,
    param_distributions=param_grid,
    n_iter=5,
    cv=2,
    scoring="accuracy",
    random_state=42,
    n_jobs=-1
)

random_search.fit(X_train, y_train)

print("Best Parameters:", random_search.best_params_)
print("Best Score:", random_search.best_score_)

Best Parameters: {'n_estimators': 50, 'min_samples_split': 4, 'max_depth': 5}
Best Score: 0.25

In [10]:
best_model = random_search.best_estimator_

best_model.fit(X_train, y_train)

y_pred = best_model.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Test Accuracy:", accuracy)

Test Accuracy: 0.5

In [12]:
print("GridSearchCV Best Score:", grid_search.best_score_)
print("RandomizedSearchCV Best Score:", random_search.best_score_)

GridSearchCV Best Score: 0.25
RandomizedSearchCV Best Score: 0.25

In [13]:
print("GridSearchCV Best Parameters")
print(grid_search.best_params_)

print()

print("RandomizedSearchCV Best Parameters")
print(random_search.best_params_)

GridSearchCV Best Parameters
{'max_depth': 2, 'min_samples_split': 4, 'n_estimators': 50}

RandomizedSearchCV Best Parameters
{'n_estimators': 50, 'min_samples_split': 4, 'max_depth': 5}

Conclusion

Performed hyperparameter tuning using GridSearchCV and RandomizedSearchCV.
Compared different combinations of Random Forest parameters.
Selected the best model based on cross-validation accuracy.
Evaluated the optimized model on the test dataset.